### ISSUE TITLE
Ken's comments on Conor's case study

### ISSUE THREAD

**Issue by nxskok** [ConorIA/tidy-intro#1]
I have some comments on your case study (which is mostly very nice). I have embedded them in the R Notebook with "xxx Ken" at the start and "xxx" at the end, to (I hope) avoid confusion with the *** that you use to separate sections. Many of them are stylistic things that may help to make the process less complex, but I think replacing this kind of code:
x <- filter(x, y>10) %>% ...
with
x <- x %>% filter(y>10) %>% ...
all the way through would be (a) consistent with me and (b) simpler to follow, since there is no longer "sometimes" a data frame at the start.

**Comment by ConorIA** [comment]
Got this in bc00dfb76c06ed0b33e408837ce98b67d449924a
